/* tslint:disable */
/* eslint-disable */
/**
 * SIMPLE TICKET SYSTEM API
 * specification file: ~/api-docs-yaml
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

